version: '3.8'

services:
  address-app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - "9001:9000"
    volumes:
      - ./src:/var/www
    networks:
      - microservices-network

  address-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: address_db
      MYSQL_USER: address_user
      MYSQL_PASSWORD: address_password
    ports:
      - "33062:3306"
    volumes:
      - address-db-data:/var/lib/mysql
    networks:
      - microservices-network

  address-nginx:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - address-app
    networks:
      - microservices-network

volumes:
  address-db-data:

networks:
  microservices-network:
    driver: bridge